apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/integration-service/config/default?ref=36560d768b111e54f61f180812e480e47da1895c
- https://github.com/konflux-ci/integration-service/config/snapshotgc?ref=36560d768b111e54f61f180812e480e47da1895c

images:
- name: quay.io/konflux-ci/integration-service
  newName: quay.io/konflux-ci/integration-service
  newTag: 36560d768b111e54f61f180812e480e47da1895c

configMapGenerator:
- name: integration-config
  literals:
    - CONSOLE_NAME="Konflux Staging"
    - CONSOLE_URL="https://console.dev.redhat.com/application-pipeline/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}"
    - CONSOLE_URL_TASKLOG="https://console.dev.redhat.com/application-pipeline/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}/logs/{{ .TaskName }}"
    - INTEGRATION_NS="integration-service"
    - PAC_SECRET="pipelines-as-code-secret"
    - GITHUBAPPLICATION_ID="github-application-id"
    - GITHUBPRIVATE_KEY="github-private-key"
- name: pipelinerun-options
  literals:
    - PIPELINE_TIMEOUT="6h"
    - TASKS_TIMEOUT="4h"
    - FINALLY_TIMEOUT="2h"

namespace: integration-service

patches:
  - path: manager_resources_patch.yaml
