apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dex
  - proxy
  - route-and-oauth.yaml
  - ../../base

images:
  - name: quay.io/konflux-ci/workspace-manager
    digest: sha256:48df30520a766101473e80e7a4abbf59ce06097a5f5919e15075afaa86bd1a2d

  - name: quay.io/konflux-ci/konflux-ui
    newTag: 399071e88c0d481658906ff86de70c24d41be5ea

namespace: konflux-ui
