apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/stonesoup-member-cluster?ref=0ee084a57a74053841570a8c05c99ebae699843c
- ../../openshift-gitops/overlays/staging
- ../../base/external-secrets
- ../../base/monitoring
- authentication

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: 0ee084a57a74053841570a8c05c99ebae699843c

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
